CREATE TABLE `user_info` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`qq` VARCHAR(100) NOT NULL,
	`state` SMALLINT(6) NOT NULL DEFAULT '0',
	`group_id` INT(11) NOT NULL DEFAULT '0',
	`created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=5;
