CREATE TABLE `user_group` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`qq` VARCHAR(50) NOT NULL,
	`name` VARCHAR(150) NULL DEFAULT NULL,
	`location` INT(11) NULL DEFAULT NULL,
	`groupType` INT(11) NULL DEFAULT NULL,
	`keyword` VARCHAR(200) NULL DEFAULT NULL,
	`decription` VARCHAR(200) NULL DEFAULT NULL,
	`created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `qq` (`qq`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
