CREATE TABLE `task_info` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`creater` VARCHAR(50) NULL DEFAULT NULL,
	`handler` VARCHAR(50) NULL DEFAULT NULL,
	`handled_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`user_group_id` INT(11) NOT NULL,
	`completed_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`state` SMALLINT(6) NOT NULL,
	`created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;