package com.alfago.weixin.common.entitys;


// Generated 2014-7-4 14:24:02 by Hibernate Tools 3.4.0.CR1

/**
 * UserBasicInfo generated by hbm2java
 */
public class UserTaskEntity extends Entity {
	
	protected String qq;
	
	protected Integer state;
	
	public UserTaskEntity() {
	}

	public UserTaskEntity(Long userId, String qq) {
	
		this.qq = qq;
		
		this.state = 0;
	}

	public String getQq() {
		return qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}
